### ISSUE TITLE
Can't redeclare "my" in "my"

### ISSUE THREAD

**Issue by eserte** [miyagawa/AnyEvent-Twitter-Stream#25]
perl 5.23.x prohibits the "my in my" construct, causing a compile error in AnyEvent::Twitter::Stream:
```
#   Failed test 'use AnyEvent::Twitter::Stream;'
#   at t/00_compile.t line 4.
#     Tried to use 'AnyEvent::Twitter::Stream'.
#     Error:  Can't redeclare "my" in "my" at /home/cpansand/.cpan/build/2015092409/AnyEvent-Twitter-Stream-0.27-NreFgu/blib/lib/AnyEvent/Twitter/Stream.pm line 62, near ", "
# Type of arg 1 to AnyEvent::Util::guard must be block or sub {} (not reference constructor) at /home/cpansand/.cpan/build/2015092409/AnyEvent-Twitter-Stream-0.27-NreFgu/blib/lib/AnyEvent/Twitter/Stream.pm line 232, near "};"
# Compilation failed in require at t/00_compile.t line 4.
# BEGIN failed--compilation aborted at t/00_compile.t line 4.
# Looks like you failed 1 test of 1.
```

**Comment by eserte** [comment]
CPAN Testers overview: http://matrix.cpantesters.org/?dist=AnyEvent-Twitter-Stream%200.27

**Comment by miyagawa** [comment]
please open a PR :)

**Comment by eserte** [comment]
Actually I am not a user of this module, I stumbled over the problem while searching for breakages caused by bleadperl.

**Comment by miyagawa** [comment]
That doesn't mean you can't contribute :)

**Comment by eserte** [comment]
Maybe I would if I was a heavy twitter user :-)

**Comment by miyagawa** [comment]
I meant: you don't need to be a user of Twitter or of this module to contribute to fixing this module to be compatible to the latest perl, and that's why you have spent time looking around the code breakages right?

**Comment by eserte** [comment]
Actually my self-assigned job is to find _unintended_ breakages in bleadperl (as input for the infamous "bleadperl breaks cpan" p5p mails). _Intended_ breakages (or other kind of fails) are just reported to the authors, so they are at least informed. Additionally I can put the ticket number into http://analysis.cpantesters.org/beforemaintrelease?pair=5.20.2:5.23.2 , so it's possible to filter out issues already acted on.
