### ISSUE TITLE
scheduled Twitter API changes ...?

### ISSUE THREAD

**Issue by gypark** [miyagawa/AnyEvent-Twitter-Stream#27]
Hello,

I've been using AnyEvent::Twitter::Stream for several years. I want to say thank you at first.

I recently heard a news like this:
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html

I'm afraid that my Perl script would stop working after those API changes are applied.
I'd like to ask if any work is doing on this module.

Thank you.

**Comment by miyagawa** [comment]
Yes, once the API is shutdown, this module and scripts using it will stop working. There's nothing that can be done about it.

**Comment by gypark** [comment]
Thanks for reply! I'll have to find a way to use new API...
